import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useState } from "react";
import { Dialog } from "@headlessui/react";
import { Bars3Icon, XMarkIcon } from "@heroicons/react/24/outline";
import Homepage from "~/components/homepage";
const navigation = [
  { name: "Product", href: "#" },
  { name: "Features", href: "#" },
  { name: "Marketplace", href: "#" },
  { name: "Company", href: "#" },
];
export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Sol City Lottery</title>
        <meta
          name="Sol City the best way to win"
          content="Generated by Sol City"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-h-screen  min-h-screen ">
        <div>
          <Homepage />
        </div>
      </main>
    </>
  );
}
