import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { HomePage } from "~/screens/HomePage";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Sol City Lottery v.0.1</title>
        <meta
          name="Sol City the best way to win"
          content="Generated by Sol City"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          test
          <HomePage />
        </div>
      </main>
    </>
  );
}
